name: bully_client
description: E2E encrypted messenger client.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  web_socket_channel: ^3.0.1
  flutter_secure_storage: ^10.3.1
  dio: ^5.5.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bonsoir: ^7.1.4
  crypto: ^3.0.6
  flutter_webrtc: ^1.5.2
  path_provider: ^2.1.5
  file_picker: ^11.0.3
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
